config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :notificacoes, only: [:index]
  resources :recompensas
  resources :faqs
  resources :dialogos, except: [:index]
  resources :comunicados
  resources :quiz_respostas_alunos, except: [:index]
  resources :dicas, except: [:index]
  resources :artefatos_alunos, except: [:show, :edit, :destroy]
  resources :eventos
  resources :badges_alunos, except: [:show, :edit, :destroy]
  resources :conversas, except: [:edit]
  resources :grupos_cursos
  resources :artefatos
  resources :grupos
  resources :quiz_pergunta_respostas
  resources :quiz_perguntas, except: [:index]
  resources :quizzes, except: [:index]
  resources :niveis
  resources :missoes, except: [:index]
  resources :badges
  resources :salas_chat
  resources :tarefa_avaliacao, except: [:index]
  resources :tarefa_alunos
  resources :tarefas, except: [:index]
  resources :avatares
  resources :foruns_comentarios, except: [:index, :show]
  resources :foruns
  resources :usuario_curso
  resources :materiais, except: [:index]
  resources :cursos
  resources :ahoy_visits, except: [:new, :edit, :destroy]

  resources :modulos do
    collection do
      patch :sort
    end
  end

  resources :modulos_ordenacoes do
    collection do
      patch :sort
    end
  end
  

  resources :tema_cursos
  devise_for :admins, :skip => [:registrations]

  devise_scope :admin do
    authenticated :admin do
      root 'controle#controle_gestor', as: :authenticated_root
    end
  end
  
  resources :usuarios, :only => [:index, :edit, :update, :show]
  devise_for :usuarios, :path_prefix => 'my', controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations',
  }

  devise_scope :usuario do
    root 'usuarios/sessions#new'
  end  

  #Controle
  get 'inicial' => 'controle#inicial'
  get 'sobre' => 'controle#sobre'
  get 'controle_gestor' => 'controle#controle_gestor'
  get 'controle_professor' => 'controle#controle_professor'
  get 'desenvolvimento' => 'controle#desenvolvimento'
  get 'contato' => 'controle#contato'

  #Usuário Curso
  get 'busca_curso' => 'usuario_curso#busca_curso'
  get 'inscricao_curso' => 'usuario_curso#inscricao_curso'
  get 'notas_aluno' => 'usuario_curso#notas_aluno'
  get 'minhas_notas' => 'usuario_curso#minhas_notas'
  get 'ranking_usuario' => 'usuario_curso#ranking_usuario'
  get 'escolher_equipe' => 'usuario_curso#escolher_equipe'
  get 'cancelar_inscricao' => 'usuario_curso#cancelar_inscricao'
  get 'finalizar_curso' => 'usuario_curso#finalizar_curso'
  get 'atualizar_avatar' => 'usuario_curso#atualizar_avatar'
  get 'pendencias' => 'usuario_curso#pendencias'
  get 'minhas_conquistas' => 'usuario_curso#minhas_conquistas'
  get 'nota_total_alunos' => 'usuario_curso#nota_total_alunos'
 
  #Curso
  get 'curso_atual' => 'cursos#atualizar_curso_atual'
  get 'descricao' => 'cursos#descricao'
  get 'visualizar_curso' => 'cursos#visualizar_curso'
  get 'notas' => 'cursos#notas'
  get 'enviar_convite' => 'cursos#enviar_convite'
  post 'enviar_convite' => 'cursos#enviar_convite'
  
  get 'finalizar_completamente_curso' => 'cursos#finalizar_completamente_curso'

  get 'material_texto' => 'materiais#texto'
  
  get 'termo_uso' => 'usuarios#termo_uso'

  get 'equipe' => 'grupos_cursos#lista_participantes'

  get 'resultado_final_quiz' => 'quiz_respostas_alunos#resultado_final_quiz'

  get 'finalizar_quiz' => 'quizzes#finalizar_quiz'

  get 'graficos_pizza' => 'question_groups#graficos_pizza'

  get 'graficos_barra' => 'question_groups#graficos_barra'

  get 'faq_agile' => 'faqs#faq_agile'

  get 'faq_agile' => 'faqs#faq_agile'

  get 'visualizar_avatares' => 'avatares#visualizar_avatares'

  get 'tarefas_avaliar' => 'tarefa_avaliacao#tarefas_avaliar'

  #Conversas
  get 'conversas_professor' => 'conversas#conversas_professor'
  get 'conversas_assunto' => 'conversas#conversas_assunto'

  get 'cancelar_evento' => 'eventos#cancelar_evento'

  #CursoCertificado
  get 'gerar_certificado' => 'curso_certificados#gerar_certificado'
  get 'validar_certificado' => 'curso_certificados#validar_certificado'
  get 'certificado_validado' => 'curso_certificados#certificado_validado'

  mount RailsAdmin::Engine => '/administration', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Ckeditor::Engine => '/ckeditor'

  mount ActionCable.server => '/cable'
  
  mount Rapidfire::Engine => "/rapidfire"

  resources :question_groups do
    get 'results', on: :member

    resources :questions
    resources :answer_groups, only: [:new, :create, :show]
  end
  resources :questions
end

app/models/faq.rb
class Faq < ApplicationRecord
    validates_presence_of :pergunta, :resposta
    self.per_page = 10
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_any!, :except => [:faq_agile, :show]

  # GET /faqs
  # GET /faqs.json
  def index
    authorize! :index, Faq
    @q = Faq.ransack(params[:q])
    @faqs = @q.result.paginate(page: params[:page])
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
    authorize! :show, Faq
  end

  # GET /faqs/new
  def new
    authorize! :new, Faq
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
    authorize! :edit, Faq
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'FAQ cadastrada com sucesso!' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to @faq, notice: 'FAQ atualizada com sucesso!' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    authorize! :destroy, Faq
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: 'FAQ excluída com sucesso!' }
      format.json { head :no_content }
    end
  end

  def faq_agile
    @q = Faq.ransack(params[:q])
    @faqs = @q.result.paginate(page: params[:page])
    render layout: 'neutro'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:pergunta, :resposta)
    end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_form.html.erb
<%= form_with(model: faq, local: true) do |form| %>
  <% if faq.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(faq.errors.count, "erro(s)") %> FAQ não pôde ser salva!</h2>

      <ul>
      <% faq.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card-body">

    <div class="form-group row">
      <label for="inputNome" class="col-md-3 col-form-label">Pergunta*</label>
      <div class="col-md-9">
        <%= form.text_field :pergunta, autofocus: true, class: "form-control", required: true %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputNome" class="col-md-3 col-form-label">Resposta*</label>
      <div class="col-md-9">
        <%= form.cktext_area :resposta, class: "form-control", required: true%>
      </div>
    </div>

  </div>

  <div class="card-footer text-muted">
    <%= form.submit "Salvar", class: "btn btn-md btn-primary" %>
    <%= link_to 'Voltar', faqs_path, class: "btn btn-md btn-secondary" %>
  </div>

<% end %>

app/views/faqs/edit.html.erb
<div class="card">
    <div class="card-header">Atualizar FAQ</div> 
	<%= render 'form', faq: @faq %>
</div>

app/views/faqs/faq_agile.html.erb
<div class="card">
  <div class="card-header">FAQ - Perguntas Frequentes</div>

  <%= search_form_for @q, url: faq_agile_path do |f| %>
    <div class="card-body">

      <div class="row">
        <div class="col-lg-6">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Pergunta</span>
            </div>
            <%= f.search_field :pergunta_cont, :class => 'form-control'  %>
          </div>
        </div>

        <div class="col-lg-6">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Resposta</span>
            </div>
            <%= f.search_field :resposta_cont, :class => 'form-control'  %>
          </div>
        </div>
      </div>     
    </div>
    
    <div class="text-center">
      <button class="btn btn-primary link search-btn" ><% submit_tag "" %>Pesquisar</button>
    </div>
  <% end %>

    <div id="accordion">
      <% @faqs.each do |faq| %>
        <div class="card">
          <div class="card-header" id="heading<%= faq.id %>">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed text-white" data-toggle="collapse" data-target="#collapse_<%= faq.id %>" aria-expanded="false" aria-controls="collapseOne">
                <%= faq.pergunta %>
              </button>
            </h5>
          </div>

          <div id="collapse_<%= faq.id %>" class="collapse" aria-labelledby="heading<%= faq.id %>" data-parent="#accordion">
            <div class="card-body">
              <%= faq.resposta.to_s.html_safe %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <p> <%= will_paginate @faqs %></p>
</div>

app/views/faqs/index.html.erb
<div class="card">
  <div class="card-header">FAQs</div>

  <%= search_form_for @q do |f| %>
    <div class="card-body">

      <div class="row">
        <div class="col-lg-6">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Pergunta</span>
            </div>
            <%= f.search_field :pergunta_cont, :class => 'form-control'  %>
          </div>
        </div>

        <div class="col-lg-6">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Resposta</span>
            </div>
            <%= f.search_field :resposta_cont, :class => 'form-control'  %>
          </div>
        </div>
      </div>     
    </div>
    
    <div class="text-center">
      <button class="btn btn-primary link search-btn" ><% submit_tag "" %>Pesquisar</button>
    </div>
  <% end %>

  <% if !@faqs.empty? %>
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead class="thead-dark">
          <tr>
            <th class="text-center">Pergunta</th>
            <th colspan="3" class="text-center">Opções</th>
          </tr>
        </thead>
        <tbody>
          <% @faqs.each do |faq| %>
            <tr>
              <td><%= faq.pergunta %></td>
              <td><%= link_to 'Visualizar', faq %></td>
              <td>
                <% if can? :edit, Faq %>
                  <%= link_to 'Atualizar', edit_faq_path(faq) %>
                <% end %>
              <td>
                <% if can? :Destroy, Faq %>
                  <%= link_to 'Excluir', faq, method: :delete, data: { confirm: 'Deseja realmente excluir a FAQ?' } %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <span> <%= will_paginate @faqs %></span>
  <% end %>

  <br>

  <div class="card-footer text-muted">
    <% if can? :new, Faq %>
      <%= link_to 'Cadastrar FAQ', new_faq_path, class: "btn btn-md btn-success" %>
    <% end %>
    <%= link_to 'Voltar', controle_gestor_path, class: "btn btn-md btn-secondary" %>
  </div>  

</div>

app/views/faqs/new.html.erb
<div class="card">
    <div class="card-header">Cadastrar FAQ</div> 
	<%= render 'form', faq: @faq %>
</div>

app/views/faqs/show.html.erb
<div class="card">

  <div class="card-header">FAQ
    <% if can? :edit, Faq %>
      <%= link_to '', edit_faq_path(@faq), class: "fa fa-edit text-white" %>
    <% end %>
    <% if can? :destroy, Faq %>
      <%= link_to '', @faq, method: :delete, data: { confirm: 'Deseja realmente excluir a FAQ?' }, class: "fa fa-trash text-white" %>
    <% end %>
  </div>
  
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <ul class="list-group">
        <li class="list-group-item"><b>Pergunta:</b> <%= @faq.pergunta %></li>
        <li class="list-group-item"><b>Resposta:</b> <%= @faq.resposta.to_s.html_safe %></li>
        <li class="list-group-item"><b>Cadastrada em:</b> <%= @faq.created_at.strftime("%d/%m/%Y - %H:%M:%S") %></li>
        <li class="list-group-item"><b>Atualizada em:</b> <%= @faq.updated_at.strftime("%d/%m/%Y - %H:%M:%S") %></li> 
      </ul>
    </div>
  </div>
  
  <br>
  
  <div class="card-footer text-muted">
    <%= link_to 'Voltar', faqs_path, class: "btn btn-md btn-secondary" %>
  </div>
</div>