config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :notificacoes, only: [:index]
  resources :recompensas
  resources :faqs
  resources :dialogos, except: [:index]
  resources :comunicados
  resources :quiz_respostas_alunos, except: [:index]
  resources :dicas, except: [:index]
  resources :artefatos_alunos, except: [:show, :edit, :destroy]
  resources :eventos
  resources :badges_alunos, except: [:show, :edit, :destroy]
  resources :conversas, except: [:edit]
  resources :grupos_cursos
  resources :artefatos
  resources :grupos
  resources :quiz_pergunta_respostas
  resources :quiz_perguntas, except: [:index]
  resources :quizzes, except: [:index]
  resources :niveis
  resources :missoes, except: [:index]
  resources :badges
  resources :salas_chat
  resources :tarefa_avaliacao, except: [:index]
  resources :tarefa_alunos
  resources :tarefas, except: [:index]
  resources :avatares
  resources :foruns_comentarios, except: [:index, :show]
  resources :foruns
  resources :usuario_curso
  resources :materiais, except: [:index]
  resources :cursos
  resources :ahoy_visits, except: [:new, :edit, :destroy]

  resources :modulos do
    collection do
      patch :sort
    end
  end

  resources :modulos_ordenacoes do
    collection do
      patch :sort
    end
  end
  

  resources :tema_cursos
  devise_for :admins, :skip => [:registrations]

  devise_scope :admin do
    authenticated :admin do
      root 'controle#controle_gestor', as: :authenticated_root
    end
  end
  
  resources :usuarios, :only => [:index, :edit, :update, :show]
  devise_for :usuarios, :path_prefix => 'my', controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations',
  }

  devise_scope :usuario do
    root 'usuarios/sessions#new'
  end  

  #Controle
  get 'inicial' => 'controle#inicial'
  get 'sobre' => 'controle#sobre'
  get 'controle_gestor' => 'controle#controle_gestor'
  get 'controle_professor' => 'controle#controle_professor'
  get 'desenvolvimento' => 'controle#desenvolvimento'
  get 'contato' => 'controle#contato'

  #Usuário Curso
  get 'busca_curso' => 'usuario_curso#busca_curso'
  get 'inscricao_curso' => 'usuario_curso#inscricao_curso'
  get 'notas_aluno' => 'usuario_curso#notas_aluno'
  get 'minhas_notas' => 'usuario_curso#minhas_notas'
  get 'ranking_usuario' => 'usuario_curso#ranking_usuario'
  get 'escolher_equipe' => 'usuario_curso#escolher_equipe'
  get 'cancelar_inscricao' => 'usuario_curso#cancelar_inscricao'
  get 'finalizar_curso' => 'usuario_curso#finalizar_curso'
  get 'atualizar_avatar' => 'usuario_curso#atualizar_avatar'
  get 'pendencias' => 'usuario_curso#pendencias'
  get 'minhas_conquistas' => 'usuario_curso#minhas_conquistas'
  get 'nota_total_alunos' => 'usuario_curso#nota_total_alunos'
 
  #Curso
  get 'curso_atual' => 'cursos#atualizar_curso_atual'
  get 'descricao' => 'cursos#descricao'
  get 'visualizar_curso' => 'cursos#visualizar_curso'
  get 'notas' => 'cursos#notas'
  get 'enviar_convite' => 'cursos#enviar_convite'
  post 'enviar_convite' => 'cursos#enviar_convite'
  
  get 'finalizar_completamente_curso' => 'cursos#finalizar_completamente_curso'

  get 'material_texto' => 'materiais#texto'
  
  get 'termo_uso' => 'usuarios#termo_uso'

  get 'equipe' => 'grupos_cursos#lista_participantes'

  get 'resultado_final_quiz' => 'quiz_respostas_alunos#resultado_final_quiz'

  get 'finalizar_quiz' => 'quizzes#finalizar_quiz'

  get 'graficos_pizza' => 'question_groups#graficos_pizza'

  get 'graficos_barra' => 'question_groups#graficos_barra'

  get 'faq_agile' => 'faqs#faq_agile'

  get 'faq_agile' => 'faqs#faq_agile'

  get 'visualizar_avatares' => 'avatares#visualizar_avatares'

  get 'tarefas_avaliar' => 'tarefa_avaliacao#tarefas_avaliar'

  #Conversas
  get 'conversas_professor' => 'conversas#conversas_professor'
  get 'conversas_assunto' => 'conversas#conversas_assunto'

  get 'cancelar_evento' => 'eventos#cancelar_evento'

  #CursoCertificado
  get 'gerar_certificado' => 'curso_certificados#gerar_certificado'
  get 'validar_certificado' => 'curso_certificados#validar_certificado'
  get 'certificado_validado' => 'curso_certificados#certificado_validado'

  mount RailsAdmin::Engine => '/administration', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Ckeditor::Engine => '/ckeditor'

  mount ActionCable.server => '/cable'
  
  mount Rapidfire::Engine => "/rapidfire"

  resources :question_groups do
    get 'results', on: :member

    resources :questions
    resources :answer_groups, only: [:new, :create, :show]
  end
  resources :questions
end

app/controllers/grupos_cursos_controller.rb
class GruposCursosController < ApplicationController
  before_action :set_grupo_curso, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!

  # GET /grupos_cursos
  # GET /grupos_cursos.json
  def index
    authorize! :index, GrupoCurso
    @grupos_cursos = GrupoCurso.where(curso_id: @perfil.curso_id
      ).page(params[:page]).order('nome_curso')
  end

  # GET /grupos_cursos/1
  # GET /grupos_cursos/1.json
  def show
    authorize! :show, GrupoCurso
    @lista_participantes = UsuarioCurso.where(grupo_curso_id: @grupo_curso.id).page(params[:page]).order('nickname')
  end

  # GET /grupos_cursos/new
  def new
    authorize! :new, GrupoCurso
    @grupo_curso = GrupoCurso.new
    @grupo_curso.curso_id = @perfil.curso_id
  end

  # GET /grupos_cursos/1/edit
  def edit
    authorize! :edit, GrupoCurso
  end

  # POST /grupos_cursos
  # POST /grupos_cursos.json
  def create
    @grupo_curso = GrupoCurso.new(grupo_curso_params)

    respond_to do |format|
      if @grupo_curso.save
        format.html { redirect_to @grupo_curso, notice: 'Equipe cadastrada com sucesso!' }
        format.json { render :show, status: :created, location: @grupo_curso }
      else
        format.html { render :new, @current_usuario => current_usuario }
        format.json { render json: @grupo_curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupos_cursos/1
  # PATCH/PUT /grupos_cursos/1.json
  def update
    respond_to do |format|
      if @grupo_curso.update(grupo_curso_params)
        format.html { redirect_to @grupo_curso, notice: 'Equipe atualizada com sucesso!' }
        format.json { render :show, status: :ok, location: @grupo_curso }
      else
        format.html { render :edit, @current_usuario => current_usuario }
        format.json { render json: @grupo_curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupos_cursos/1
  # DELETE /grupos_cursos/1.json
  def destroy
    authorize! :destroy, GrupoCurso
    
    respond_to do |format|
      if @grupo_curso.destroy
        format.html { redirect_to grupos_cursos_url, notice: 'Equipe excluída com sucesso!' }
        format.json { head :no_content }
      else
        format.html { redirect_to grupos_cursos_url, alert: 'A Equipe não pôde ser excluída, pois está sendo utilizada!' }
        format.json { head :no_content }
      end
    end
  end

  def lista_participantes
    authorize! :lista_participantes, :grupo_curso
    @lista_participantes = UsuarioCurso.where(grupo_curso_id: @perfil.grupo_curso_id).page(params[:page]).order('nickname')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupo_curso
      @grupo_curso = GrupoCurso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grupo_curso_params
      params.require(:grupo_curso).permit(:grupo_id, :curso_id, :nome_curso)
    end
end

app/helpers/grupos_cursos_helper.rb
module GruposCursosHelper
end

app/views/grupos_cursos/_form.html.erb
<%= form_with(model: grupo_curso, local: true) do |form| %>
  <% if grupo_curso.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(grupo_curso.errors.count, "erro(s)") %> - Grupo do Curso não pôde ser salvo!</h2>

      <ul>
      <% grupo_curso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card-body">

    <%= form.hidden_field :curso_id %>

    <div class="form-group row">
      <% Grupo.where(ativo: true).each do |grupo| %>      
        <div class="col-md-4 text-center">
          <p><%= image_tag grupo.imagem.variant(resize: "200x200"), class: "img-responsive img-thumbnail" %></p>
          <p><%= form.radio_button :grupo_id, grupo.id %>
          <b><%= grupo.nome %></b> - Perfil: <%= grupo.perfil %></p>
          <p><%= link_to 'Ver Avatares', visualizar_avatares_path(grupo_id: grupo.id) %></p>
      </div>
      <% end %>      
    </div>

    <div class="form-group row">
      <label for="inputNome" class="col-md-4 col-form-label">Nome da Equipe no curso*</label>
      <div class="col-md-8">
        <%= form.text_field :nome_curso, autofocus: true, class: "form-control", required: true %>
      </div>
    </div>

  </div>

  <div class="card-footer text-muted">
    <%= form.submit "Salvar", class: "btn btn-md btn-primary" %>
    <%= link_to 'Voltar', grupos_cursos_path, class: "btn btn-md btn-secondary" %>
  </div>

<% end %>

app/views/grupos_cursos/edit.html.erb
<div class="card">
    <div class="card-header">Atualizar Equipe do Curso</div> 
	<%= render 'form', grupo_curso: @grupo_curso %>
</div>

app/views/grupos_cursos/index.html.erb
<div class="card">
  <div class="card-header">Equipes do Curso</div>

  <% if !@grupos_cursos.empty? %>
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead class="thead-dark">
          <tr>
            <th class="text-center">Nome</th>
            <th class="text-center">Perfil</th>
            <th colspan="3" class="text-center">Opções</th>
          </tr>
        </thead>
        <tbody>
          <% @grupos_cursos.each do |grupo_curso| %>
            <tr>
              <td><%= grupo_curso.nome_curso %></td>
              <td><%= grupo_curso.grupo.perfil %></td>
              <% if can? :show, GrupoCurso %>
                <td><%= link_to 'Visualizar', grupo_curso %></td>
              <% end %>
              <td>
                <% if can? :edit, GrupoCurso %>
                  <%= link_to 'Atualizar', edit_grupo_curso_path(grupo_curso) %>
                <% else%> - 
                <% end %>
              <td>
                <% if can? :Destroy, GrupoCurso %>
                  <%= link_to 'Excluir', grupo_curso, method: :delete, data: { confirm: 'Deseja realmente excluir a Equipe do Curso?' } %>
                <% else%> - 
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <span> <%= will_paginate @grupos_cursos %></span>
  <% else %>
    <div class="alert alert-danger">Não há Equipes cadastradas! Por favor, cadastre pelo menos uma equipe para Alunos e uma equipe para Professores.</div>
  <% end %>

  <br>

  <% if can? :new, GrupoCurso %>
    <div class="card-footer text-muted">
      <%= link_to 'Cadastrar Equipe no Curso', new_grupo_curso_path, class: "btn btn-md btn-success" %>
    </div>
  <% end %>

</div>

app/views/grupos_cursos/lista_participantes.html.erb
<% if @perfil.grupo_curso %>
  <div class="card">
    <div class="card-header">
      <p>Equipe <%= @perfil.grupo_curso.nome_curso %></p>
      <p><%= image_tag @perfil.grupo_curso.grupo.imagem.variant(resize: "400x400"), class: 'img-responsive img-thumbnail' %></p>
    </div>

    <div class="alert alert-success">
      <p>Pontuação Total da Equipe: <%= formata_pontos(@perfil.grupo_curso.pontuacao_total_equipe) %></p>
      <p>Pontuação Média da Equipe: <%= formata_pontos(@perfil.grupo_curso.pontuacao_media_equipe) %></p>
    </div>

    <div class="card-header bg-primary">Membros da Equipe</div>
    <div class="container-fluid">
      <div class="row">
        <% @lista_participantes.each do |participante| %>
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white o-hidden h-200 curso">
              <div class="card-body">
                <% if participante.avatar %>
                  <%= image_tag participante.avatar.imagem, class: "img-fluid img-responsive" %>
                <% else %>
                  <%= image_tag "missing.png", class: "img-responsive img-thumbnail" %>
                <% end %>
              </div>
              <div class="card-footer bg-primary text-white">
                <div>
                  <ul class="list-unstyled components">
                  <li><%= link_to participante.nickname, participante, class: "text-white" %></li>
                  <li><b>XP:</b> <%= pontuacao(participante) %></li>
                  <li><b><%= participante.nivel.nome %></b></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>

  <div class="card">
    <div class="card-header">Equipe</div>
    <div class="alert alert-danger" role="alert">
      Você ainda não faz parte de nenhuma Equipe. Clique em 'Escolher Equipe' para escolher a Equipe que gostaria de fazer parte.  Em caso de dúvidas, entre em contato com o Professor do curso.
    </div>

    <div class="text-center">
      <%= link_to 'Escolher Equipe', escolher_equipe_url(id: @perfil.id), class: "btn btn-md btn-primary" %>
    </div>
  </div>

<% end %>

app/views/grupos_cursos/new.html.erb
<div class="card">
    <div class="card-header">Cadastrar Equipe do Curso</div> 
	<%= render 'form', grupo_curso: @grupo_curso %>
</div>

app/views/grupos_cursos/show.html.erb
<div class="card">
	<div class="card-header">Equipe
	    <% if can? :edit, GrupoCurso %>
	      <%= link_to '', edit_grupo_curso_path(@grupo_curso), class: "fa fa-edit text-white" %>
	    <% end %>
	    <% if can? :destroy, GrupoCurso %>
	      <%= link_to '', @grupo_curso, method: :delete, data: { confirm: 'Deseja realmente excluir a Equipe?' }, class: "fa fa-trash text-white" %>
	    <% end %>
  	</div>

  <div class="card-body">

	    <div class="row">
	      	<div class="col-lg-4">
	        	<div class="input-group mb-3">
	        		<%= image_tag @grupo_curso.grupo.imagem.variant(resize: "300x300"), class: "img-responsive img-thumbnail" %>
	       		</div>
	      	</div>

	      	<div class="col-lg-8">
		        <div class="input-group mb-3">
		        	<p> 
			          	<label>Nome da equipe no curso: </label>          
			          	<%= @grupo_curso.nome_curso %>
		        	</p>
		        </div>

		        <div class="input-group mb-3">
		        	<p> 
			          	<label>Nome padrão da equipe: </label>          
			          	<%= @grupo_curso.grupo.nome %>
		        	</p>
		        </div>

		        <div class="input-group mb-3">
		        	<p> 
			          	<label>Cadastrado em: </label>          
			          	<%= @grupo_curso.created_at.strftime("%d/%m/%Y - %H:%M:%S") %>
		        	</p>
		        </div>
		    </div>
		</div>
	</div>

	<br>

	<% if !@lista_participantes.empty? %>
	  <div class="card">
	    <div><br></div>
	    <div class="card-header bg-primary">Membros da Equipe</div>
	    <div class="container-fluid">
	      <div class="row">
	        <% @lista_participantes.each do |participante| %>
	          <div class="col-xl-3 col-sm-6 mb-3">
	            <div class="card text-white o-hidden h-200 curso">
	              <div class="card-body">
	              	<% if participante.avatar %>
	                	<%= image_tag participante.avatar.imagem.variant(resize: "200x200"), class: "img-responsive img-thumbnail" %>
	                <% else %>
	                	<p class="list-group-item text-center"><%= image_tag "missing.png", class: "img-responsive img-thumbnail" %></p>
	                <% end %>
	              </div>
	              <div class="card-footer bg-primary text-white">
	                <div><%= link_to participante.nickname, participante, class: "text-white font-weight-bold" %></div>
	              </div>
	            </div>
	          </div>
	        <% end %>
	      </div>
	    </div>
	  </div>
	<% end %>

	<div class="card-footer text-muted">
	  <%= link_to 'Voltar', grupos_cursos_path, class: "btn btn-md btn-secondary" %>
	</div>
</div>