config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :notificacoes, only: [:index]
  resources :recompensas
  resources :faqs
  resources :dialogos, except: [:index]
  resources :comunicados
  resources :quiz_respostas_alunos, except: [:index]
  resources :dicas, except: [:index]
  resources :artefatos_alunos, except: [:show, :edit, :destroy]
  resources :eventos
  resources :badges_alunos, except: [:show, :edit, :destroy]
  resources :conversas, except: [:edit]
  resources :grupos_cursos
  resources :artefatos
  resources :grupos
  resources :quiz_pergunta_respostas
  resources :quiz_perguntas, except: [:index]
  resources :quizzes, except: [:index]
  resources :niveis
  resources :missoes, except: [:index]
  resources :badges
  resources :salas_chat
  resources :tarefa_avaliacao, except: [:index]
  resources :tarefa_alunos
  resources :tarefas, except: [:index]
  resources :avatares
  resources :foruns_comentarios, except: [:index, :show]
  resources :foruns
  resources :usuario_curso
  resources :materiais, except: [:index]
  resources :cursos
  resources :ahoy_visits, except: [:new, :edit, :destroy]

  resources :modulos do
    collection do
      patch :sort
    end
  end

  resources :modulos_ordenacoes do
    collection do
      patch :sort
    end
  end
  

  resources :tema_cursos
  devise_for :admins, :skip => [:registrations]

  devise_scope :admin do
    authenticated :admin do
      root 'controle#controle_gestor', as: :authenticated_root
    end
  end
  
  resources :usuarios, :only => [:index, :edit, :update, :show]
  devise_for :usuarios, :path_prefix => 'my', controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations',
  }

  devise_scope :usuario do
    root 'usuarios/sessions#new'
  end  

  #Controle
  get 'inicial' => 'controle#inicial'
  get 'sobre' => 'controle#sobre'
  get 'controle_gestor' => 'controle#controle_gestor'
  get 'controle_professor' => 'controle#controle_professor'
  get 'desenvolvimento' => 'controle#desenvolvimento'
  get 'contato' => 'controle#contato'

  #Usuário Curso
  get 'busca_curso' => 'usuario_curso#busca_curso'
  get 'inscricao_curso' => 'usuario_curso#inscricao_curso'
  get 'notas_aluno' => 'usuario_curso#notas_aluno'
  get 'minhas_notas' => 'usuario_curso#minhas_notas'
  get 'ranking_usuario' => 'usuario_curso#ranking_usuario'
  get 'escolher_equipe' => 'usuario_curso#escolher_equipe'
  get 'cancelar_inscricao' => 'usuario_curso#cancelar_inscricao'
  get 'finalizar_curso' => 'usuario_curso#finalizar_curso'
  get 'atualizar_avatar' => 'usuario_curso#atualizar_avatar'
  get 'pendencias' => 'usuario_curso#pendencias'
  get 'minhas_conquistas' => 'usuario_curso#minhas_conquistas'
  get 'nota_total_alunos' => 'usuario_curso#nota_total_alunos'
 
  #Curso
  get 'curso_atual' => 'cursos#atualizar_curso_atual'
  get 'descricao' => 'cursos#descricao'
  get 'visualizar_curso' => 'cursos#visualizar_curso'
  get 'notas' => 'cursos#notas'
  get 'enviar_convite' => 'cursos#enviar_convite'
  post 'enviar_convite' => 'cursos#enviar_convite'
  
  get 'finalizar_completamente_curso' => 'cursos#finalizar_completamente_curso'

  get 'material_texto' => 'materiais#texto'
  
  get 'termo_uso' => 'usuarios#termo_uso'

  get 'equipe' => 'grupos_cursos#lista_participantes'

  get 'resultado_final_quiz' => 'quiz_respostas_alunos#resultado_final_quiz'

  get 'finalizar_quiz' => 'quizzes#finalizar_quiz'

  get 'graficos_pizza' => 'question_groups#graficos_pizza'

  get 'graficos_barra' => 'question_groups#graficos_barra'

  get 'faq_agile' => 'faqs#faq_agile'

  get 'faq_agile' => 'faqs#faq_agile'

  get 'visualizar_avatares' => 'avatares#visualizar_avatares'

  get 'tarefas_avaliar' => 'tarefa_avaliacao#tarefas_avaliar'

  #Conversas
  get 'conversas_professor' => 'conversas#conversas_professor'
  get 'conversas_assunto' => 'conversas#conversas_assunto'

  get 'cancelar_evento' => 'eventos#cancelar_evento'

  #CursoCertificado
  get 'gerar_certificado' => 'curso_certificados#gerar_certificado'
  get 'validar_certificado' => 'curso_certificados#validar_certificado'
  get 'certificado_validado' => 'curso_certificados#certificado_validado'

  mount RailsAdmin::Engine => '/administration', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Ckeditor::Engine => '/ckeditor'

  mount ActionCable.server => '/cable'
  
  mount Rapidfire::Engine => "/rapidfire"

  resources :question_groups do
    get 'results', on: :member

    resources :questions
    resources :answer_groups, only: [:new, :create, :show]
  end
  resources :questions
end

app/controllers/usuario_curso_controller.rb
class UsuarioCursoController < ApplicationController
  before_action :set_usuario_curso, only: [:show, :edit, :update, :destroy, :escolher_equipe, :cancelar_inscricao, :finalizar_curso, :atualizar_avatar]
  before_action :authenticate_usuario!
  
  # GET /usuario_curso
  # GET /usuario_curso.json
  def index
    @q = UsuarioCurso.where(curso_id: current_usuario.curso_atual_id).ransack(params[:q])
    @usuario_curso = @q.result.paginate(page: params[:page]).order('nickname')
    authorize! :index, UsuarioCurso
  end

  # GET /usuario_curso/1
  # GET /usuario_curso/1.json
  def show
    authorize! :show, UsuarioCurso
    @badges = BadgeAluno.where(usuario_curso_id: @usuario_curso.id) 
    @artefatos = ArtefatoAluno.where(usuario_curso_id: @usuario_curso.id) 
    authorize! :show, UsuarioCurso
  end

  # GET /usuario_curso/new
  def new
    authorize! :new, UsuarioCurso
    @usuario_curso = UsuarioCurso.new
    @usuario_curso.curso_id = params[:curso_id]
  end

  # GET /usuario_curso/1/edit
  def edit
    authorize! :edit, UsuarioCurso
  end

  # POST /usuario_curso
  # POST /usuario_curso.json
  def create
    @usuario_curso = UsuarioCurso.new(usuario_curso_params)
    @usuario_curso.nivel_id = 1
    respond_to do |format|
      if @usuario_curso.save
        ApplicationMailer.cadastro_curso(@usuario_curso).deliver      
        format.html { redirect_to @usuario_curso, notice: 'Usuário cadastrado no Curso com sucesso!' }
        format.json { render :show, status: :created, location: @usuario_curso }
      else
        format.html { render :new, @current_usuario => current_usuario }
        format.json { render json: @usuario_curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuario_curso/1
  # PATCH/PUT /usuario_curso/1.json
  def update
    respond_to do |format|
      if @usuario_curso.update(usuario_curso_params)
        format.html { redirect_to @usuario_curso, notice: 'Usuário do Curso atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @usuario_curso }
      else
        format.html { render :edit, @current_usuario => current_usuario }
        format.json { render json: @usuario_curso.errors, status: :unprocessable_entity }
      end
    end
  end

  def busca_curso
    if not params[:codigo_acesso]
      render layout: 'neutro'
    else
      @curso = Curso.where(codigo_acesso: params[:codigo_acesso]).first
      respond_to do |format|
        if not @curso.blank?
          @usuario_curso = UsuarioCurso.new(perfil: 'Aluno', nickname: current_usuario.nome, usuario_id: current_usuario.id, curso_id: @curso.id, nivel_id: 1)
          if @usuario_curso.save
            format.html { redirect_to @usuario_curso, @current_usuario => current_usuario, notice: 'Usuário do Curso cadastrado com sucesso!' }
            format.json { render :show, status: :created, location: @usuario_curso }
          else
            format.html { render :busca_curso, @current_usuario => current_usuario, layout: 'neutro' }
            format.json { render json: @usuario_curso.errors, status: :unprocessable_entity }
          end
        else
          format.html { redirect_to busca_curso_path, alert: 'Curso não encontrado!' }
        end
      end
    end
  end

  def inscricao_curso
    @usuario_curso = UsuarioCurso.new(perfil: 'Aluno', nickname: current_usuario.nome, usuario_id: current_usuario.id, curso_id: current_usuario.curso_atual_id, nivel_id: 1, )
    if @usuario_curso.save
      flash[:notice] = 'Usuário do Curso cadastrado com sucesso!'
      redirect_to :controller => "cursos", :action => "show", id: current_usuario.curso_atual_id
    else
      format.html { render :back }
      format.json { render json: @usuario_curso.errors, status: :unprocessable_entity }
    end
  end

  def notas_aluno
    authorize! :notas_aluno,:notas
    @aluno = UsuarioCurso.find_by('usuario_curso.id = ? and curso_id = ?',
       params[:aluno_id], params[:curso_id])
    respond_to do |format|
      format.html
      format.xls
      format.pdf do
        render pdf: "Notas do Aluno",
                page_size: "A4",
                title: "Notas do Aluno",
                orientation: 'Landscape', 
                layout: 'application'
      end
    end
  end

  def nota_total_alunos
    authorize! :notas_aluno,:notas
    @alunos = UsuarioCurso.where('curso_id = ? and perfil =?', @perfil.curso_id, "Aluno").order('nickname')
    respond_to do |format|
      format.html
      format.xls
      format.pdf do
        render pdf: "Notas da Turma",
                page_size: "A4",
                title: "Notas da Turma",
                orientation: 'Landscape', 
                layout: 'application'
      end
    end
  end

  def minhas_notas
    @modulos = Modulo.where('modulos.curso_id = ?',
       current_usuario.curso_atual_id)
    authorize! :minhas_notas,:notas
  end

  def ranking_usuario
    alunos = {}
    usuarios = UsuarioCurso.where(curso_id: current_usuario.curso_atual_id, perfil: 'Aluno').order('created_at desc')
    for usuario in usuarios
			alunos[usuario] = usuario.pontuacao.to_f
		end
    @alunos = Hash[alunos.sort_by{|k, v| v}.reverse]
    authorize! :show, UsuarioCurso
  end

  def atualizar_avatar
    authorize! :edit, UsuarioCurso
  end

  def escolher_equipe
    authorize! :escolher_equipe, UsuarioCurso
  end

  def cancelar_inscricao
    authorize! :cancelar_inscricao, UsuarioCurso
    @usuario_curso.status_curso = 'Inscrição Cancelada'
    if @usuario_curso.save
      flash[:notice] = 'Inscrição no curso Cancelada com sucesso!'
      redirect_to :controller => "cursos", :action => "show", id: current_usuario.curso_atual_id
      ApplicationMailer.inscricao_cancelada(@usuario_curso).deliver    
    end
  end

  def finalizar_curso
    authorize! :finalizar_curso, UsuarioCurso
    @usuario_curso.status_curso = 'Curso finalizado'
    @usuario_curso.curso_finalizado = true
    @usuario_curso.aprovado = @usuario_curso.verifica_aprovacao
    if @usuario_curso.save
      flash[:notice] = 'Curso finalizado com sucesso!'
    end
    redirect_to :controller => "cursos", :action => "show", id: current_usuario.curso_atual_id
  end

  def pendencias
    authorize! :pendencias, UsuarioCurso
    @usuario_curso = UsuarioCurso.find(params[:id])
    @tarefas = Tarefa.joins(missao: :modulo).where('modulos.curso_id =?', @usuario_curso.curso_id).where.not(id: TarefaAluno.joins(tarefa: [missao: :modulo]).select('tarefa_alunos.tarefa_id').where('modulos.curso_id = ? and tarefa_alunos.usuario_curso_id =?', @usuario_curso.curso_id, @usuario_curso.id)).order('missoes.data_inicio')
    @quizzes = Quiz.joins(missao: :modulo).where('modulos.curso_id =?', @usuario_curso.curso_id).where.not(id: QuizRespostaAluno.joins(quiz: [missao: :modulo]).select('quiz_respostas_alunos.quiz_id').where('modulos.curso_id = ? and quiz_respostas_alunos.usuario_curso_id =?', @usuario_curso.curso_id, @usuario_curso.id)).group('quizzes.id').order('id')
    @pesquisas = QuestionGroup.where(curso_id: @usuario_curso.curso_id).where.not(id: AnswerGroup.joins(:question_group).select('answer_groups.question_group_id').where('question_groups.curso_id =? and answer_groups.usuario_curso_id =?', @usuario_curso.curso_id, @usuario_curso.id)).order('id')
  end

  def minhas_conquistas
    authorize! :minhas_conquistas, UsuarioCurso
    @usuario_curso = UsuarioCurso.find(@perfil.id)
    @badges = BadgeAluno.where(usuario_curso_id: @perfil.id).order('created_at desc')
    @artefatos = ArtefatoAluno.where(usuario_curso_id: @perfil.id).order('created_at desc')
    Notificacao.where(usuario_curso_id: @perfil.id).update_all(visualizada: true)
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario_curso
      @usuario_curso = UsuarioCurso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_curso_params
      params.require(:usuario_curso).permit(:perfil, :nickname, :pontos_experiencia, :usuario_id, :curso_id, :avatar_id, :grupo_curso_id, :nivel_id, :curso_finalizado, :status_curso, :aprovado)
    end
end

app/helpers/usuario_curso_helper.rb
module UsuarioCursoHelper

    def pontuacao usuario
        @pontuacao_tarefas = TarefaAluno.joins(:tarefa_avaliacao).where('tarefa_alunos.usuario_curso_id = ?', usuario.id).sum(:nota)
        @pontuacao_quizzes = QuizRespostaAluno.joins(:quiz_pergunta_resposta, :quiz_pergunta).where('quiz_respostas_alunos.usuario_curso_id = ? and quiz_pergunta_respostas.correta =? ', usuario.id, true).sum('quiz_perguntas.pontuacao')
        @pontuacao_total = @pontuacao_tarefas + @pontuacao_quizzes

        return  "%g" % ("%.2f" % @pontuacao_total)
    end
end

app/views/usuario_curso/_form.html.erb
<%= form_with(model: usuario_curso, local: true) do |form| %>
  <% if usuario_curso.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(usuario_curso.errors.count, "erro(s)") %> - Usuário não pôde ser cadastrado no curso!</h2>

      <ul>
      <% usuario_curso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :curso_id %>

  <div class="card-body">  
    <% if @perfil.perfil == "Professor" %>

      <div class="form-group row">
        <label for="inputNome" class="col-md-3 col-form-label">Perfil*</label>
        <div class="col-md-9">
          <%= form.select :perfil,  options_for_select([["Aluno", "Aluno"], ["Professor", "Professor"]], form.object.perfil), class: "form-control" %>
        </div>
      </div>

      <% if @usuario_curso.new_record? %>
        <div class="form-group row">
          <label for="inputNome" class="col-md-3 col-form-label">Usuário</label>
          <div class="col-md-9">
            <%= form.collection_select(:usuario_id, Usuario.where(ativo: true).order('nome'), :id, :nome, {:prompt => true}, {class: "selecionar"})%>
          </div>
        </div>
      <% else %>
        <div class="form-group row">
          <label for="inputNome" class="col-md-3 col-form-label">Usuário</label>
          <div class="col-md-9">
            <%= @usuario_curso.usuario.nome %>
          </div>
        </div>
      <% end %>

    <% end %>

    <div class="form-group row">
      <label for="inputNome" class="col-md-3 col-form-label">Nickname no curso*</label>
      <div class="col-md-9">
        <%= form.text_field :nickname, class: "form-control" %> 
      </div>
    </div>

  </div>
  
  <div class="card-footer text-muted">
    <%= form.submit "Salvar", class: "btn btn-md btn-primary" %>
    <%= link_to 'Voltar', @usuario_curso, class: "btn btn-md btn-secondary" %>
  </div>
<% end %>

app/views/usuario_curso/_minhas_conquistas.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header card-header">
      <h5 class="modal-title font-weight-bold" id="exampleModalLabel">Minhas Conquistas</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true" class="text-white">&times;</span>
      </button>
    </div>
    <div class="modal-body">

      <div class="card-header bg-primary">Nível</div>

      <div class="row">

        <div class="col-lg-3">
          <div class="input-group mb-3">
            <% if @usuario_curso.avatar %>  
              <%= image_tag @usuario_curso.avatar.imagem.variant(resize: "200x200"), class: "img-responsive img-thumbnail" %>
            <% else %>
              <%= image_tag "missing.png", class: "img-responsive img-thumbnail" %>
            <% end %>
          </div>
        </div>

        <div class="col-lg-6">
          <div class="input-group">
            <p><label>Nickname (apelido): </label>          
            <%= @usuario_curso.nickname %></p>
          </div>

          <div class="input-group">
            <p><label>Pontos de experiência (XP): </label>          
            <%= pontuacao(@usuario_curso) %></p>
          </div>

          <div class="input-group">
            <p><label>Aproveitamento das Missões: </label>          
            <%= formata_pontos(@usuario_curso.porcentagem_aprovacao) %>%</p>
          </div>

          <% if @usuario_curso.grupo_curso %>
            <div class="input-group">
              <p><label>Equipe: </label>          
              <%= @usuario_curso.grupo_curso.nome_curso %></p>
            </div>
          <% end %>
            
        </div>

        <div class="col-lg-3">
          <div class="input-group mb-2">
            <%= image_tag @usuario_curso.nivel.imagem.variant(resize: "150x150"), class: "img-responsive img-thumbnail text-center" %>
          </div>
          <div class="input-group">
            <p><label><%= @usuario_curso.nivel.nome %></label></p>
          </div>
        </div>    
    
      </div>

      <% if !@badges.empty? %>
      
        <div class="card-header bg-primary">Badges</div>

        <div class="row">
          <% @badges.each do |badge| %>
            <div class="col-xl-4 col-sm-4 mb-3">
              <div class="card text-white o-hidden h-200 curso">
                <div class="card-body">
                  <%= image_tag badge.badge.imagem.variant(resize: "300x300"), class: "img-responsive img-thumbnail" %>
                </div>
                <div class="card-footer bg-info text-white">
                  <div><b>Badge:</b> <%= badge.badge.nome %></div>
                  <div><b>Conquista:</b> <%= badge.created_at.strftime("%d/%m/%Y - %H:%M:%S") %></div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
   
      <% end %>

      <% if !@artefatos.empty? %>

        <div class="card-header bg-primary">Artefatos</div>

        <div class="row">
          <% @artefatos.each do |artefato| %>
            <div class="col-xl-4 col-sm-4 mb-3">
              <div class="card text-white o-hidden h-200 curso">
                <div class="card-body">
                  <%= image_tag artefato.artefato.imagem.variant(resize: "300x300"), class: "img-responsive img-thumbnail" %>
                </div>
                <div class="card-footer bg-info text-white">
                  <div><b>Artefato:</b> <%= artefato.artefato.nome %></div>
                  <div><b>Conquista:</b> <%= artefato.created_at.strftime("%d/%m/%Y - %H:%M:%S") %></div>
                </div>
              </div>
            </div>
          <% end %>
        </div>

      <% end %>

    </div>
    <div class="card-footer text-muted">
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
    </div>
  </div>
</div>

app/views/usuario_curso/atualizar_avatar.html.erb
<div class="card">
    <div class="card-header">Atualizar Avatar</div> 
  <%= form_with(model: @usuario_curso, local: true) do |form| %>
    <% if @usuario_curso.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(@usuario_curso.errors.count, "erro(s)") %> - Avatar não pode ser atualizado!</h2>

        <ul>
        <% @usuario_curso.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


    <div class="card-body">

      <div class="form-group row">
        <% Avatar.where(grupo_id: @perfil.grupo_curso.grupo.id, perfil: @perfil.perfil, ativo: true).each do |avatar| %>
          <div class="col-md-4">
            <p><%= image_tag avatar.imagem.variant(resize: "200x200"), class: "img-responsive img-thumbnail" %></p>
            <p><%= form.radio_button :avatar_id, avatar.id %>
               <%= avatar.nome %></p>
          </div>
        <% end %>      
      </div>    

    </div>
    
    <div class="card-footer text-muted">
      <%= form.submit "Salvar", class: "btn btn-md btn-primary" %>
      <%= link_to 'Voltar', @usuario_curso, class: "btn btn-md btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/usuario_curso/minhas_conquistas.js.erb
$("#modal-window").html("<%= escape_javascript(render 'usuario_curso/minhas_conquistas') %>");

app/views/usuario_curso/minhas_notas.html.erb
<div class="card">

  <div class="card-header">Minhas Notas </div>

	<% if !@modulos.empty? %>
		<% @modulos.each do |modulo| %>
		    <h5 class="p-3 mb-2 bg-info text-white text-center"><b>Módulo:</b> <%= modulo.nome %></h5>
		    <% Missao.where(modulo_id: modulo.id, publico: true).each do |missao| %>
			    <h6 class="p-3 mb-2 bg-secondary text-white text-center">
			    	<b>Missão (<%= missao.tipo %>):</b> <%= link_to missao.nome, missao, class: "text-light" %></h6>
			    <% if missao.tipo == 'Tarefa' %>
			    	<%= render partial: "tarefas/tarefas", locals: {tarefa: missao.tarefa} %>
			    <% end %>
			    <% if missao.tipo == 'Quiz' %>
			    	<%= render partial: "quizzes/quizzes", locals: {quiz: missao.quiz} %>
			    <% end %>
			<% end %>
		<% end %>
	<% end %>
	<h6 class="p-3 mb-2 bg-success text-white text-center"><b>Pontuação Total:</b> <%= pontuacao(@perfil) %></h5>
</div>

app/views/usuario_curso/show.html.erb
<div class="card">

  <div class="card-header">Ficha de atributos</div>

  <div class="card-body">

    <div class="row">

      <div class="col-lg-3">
        <div class="input-group mb-3">
          <% if @usuario_curso.avatar %>  
            <%= image_tag @usuario_curso.avatar.imagem.variant(resize: "300x300"), class: "img-responsive img-thumbnail" %>
            <% else %>
              <%= image_tag "missing.png", class: "img-responsive img-thumbnail" %>
            <% end %>
        </div>
      </div>

      <div class="col-lg-6">
        <% if @perfil.perfil == "Professor" %>
          <div class="input-group">
            <p> <label>Nome: </label>          
            <%= @usuario_curso.usuario.nome %></p>
          </div>

          <div class="input-group">
            <p><label>Perfil: </label>          
            <%= @usuario_curso.perfil %></p>
          </div>
        <% end %>

        <div class="input-group">
          <p><label>Nickname (apelido): </label>          
          <%= @usuario_curso.nickname %></p>
        </div>

        <% if @perfil.perfil != 'Professor' or @perfil.id != @usuario_curso.id %>
          <div class="input-group">
            <p><label>Pontos de experiência(XP): </label>          
            <%= pontuacao(@usuario_curso) %></p>
          </div>

          <div class="input-group">
            <p><label>Aproveitamento das Missões: </label>          
            <%= formata_pontos(@usuario_curso.porcentagem_aprovacao) %>%</p>
          </div>
        <% end %>

        <div class="input-group">
          <p><label>Cadastro no curso: </label>          
          <%= @usuario_curso.created_at.strftime("%d/%m/%Y - %H:%M:%S") %></p>
        </div>
      </div>

      <div class="col-lg-3">
        <% if @usuario_curso.perfil != 'Professor' %>
          <div class="input-group mb-2">
            <%= image_tag @usuario_curso.nivel.imagem.variant(resize: "150x150"), class: "img-responsive img-thumbnail text-center" %>
          </div>
          <div class="input-group">
            <p>
              <label><%= @usuario_curso.nivel.nome %></label>
            </p>
          </div>
        <% end %>
        <% if @usuario_curso.grupo_curso %>
          <div class="input-group mb-2">
            <%= image_tag @usuario_curso.grupo_curso.grupo.imagem.variant(resize: "150x150"), class: "img-responsive img-thumbnail text-center" %>
          </div>

          <div class="input-group">
            <p>
              <label>Equipe: <%= @usuario_curso.grupo_curso.nome_curso %></label>
            </p>
          </div>
        <% end %>
      </div>    
   
    </div>
    <% if !@usuario_curso.avatar %> 
      <div class="alert alert-success">Só é possível alterar o Avatar se você fizer parte de uma Equipe!</div>
    <% end %>
    </div>

  <% if @usuario_curso.perfil != 'Professor' %>
    
    <% if !@badges.empty? %>

      <div class="card-header">Badges</div>

      <div class="card-body">

        <div class="row">
          <% @badges.each do |badge| %>
            <div class="col-lg-2">
              <div class="input-group mb-3">
                <%= image_tag badge.badge.imagem.variant(resize: "300x300"), class: "img-responsive img-thumbnail" %>
              </div>
              <div class="input-group">
                <p>
                  <label><%= badge.badge.nome %></label>
                </p>
              </div>
            </div>
          <% end %>
        </div>    
      </div>
    <% end %>

    <% if !@artefatos.empty? %>

      <div class="card-header">Artefatos</div>

      <div class="card-body">

        <div class="row">
          <% @artefatos.each do |artefato| %>
            <div class="col-lg-2">
              <div class="input-group mb-3">
                <%= image_tag artefato.artefato.imagem.variant(resize: "300x300"), class: "img-responsive img-thumbnail" %>
              </div>
              <div class="input-group">
                <p>
                  <label><%= artefato.artefato.nome %></label>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      </div>    
      
    <% end %>
  <% end %>

  <br>
  <div class="card-footer text-muted">
    <% if @usuario_curso.grupo_curso and @usuario_curso.id == @perfil.id %>
      <%= link_to 'Atualizar Avatar', atualizar_avatar_path(id: @usuario_curso.id), class: "btn btn-md btn-warning" %>
    <% end %>
    <% if @perfil.perfil == 'Professor' or @usuario_curso.id == @perfil.id %>
      <%= link_to 'Atualizar', edit_usuario_curso_path(@usuario_curso), class: "btn btn-md btn-primary" %>
    <% end %>
    <%= link_to 'Voltar', :back, class: "btn btn-md btn-secondary" %>
  </div>

</div>