config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :notificacoes, only: [:index]
  resources :recompensas
  resources :faqs
  resources :dialogos, except: [:index]
  resources :comunicados
  resources :quiz_respostas_alunos, except: [:index]
  resources :dicas, except: [:index]
  resources :artefatos_alunos, except: [:show, :edit, :destroy]
  resources :eventos
  resources :badges_alunos, except: [:show, :edit, :destroy]
  resources :conversas, except: [:edit]
  resources :grupos_cursos
  resources :artefatos
  resources :grupos
  resources :quiz_pergunta_respostas
  resources :quiz_perguntas, except: [:index]
  resources :quizzes, except: [:index]
  resources :niveis
  resources :missoes, except: [:index]
  resources :badges
  resources :salas_chat
  resources :tarefa_avaliacao, except: [:index]
  resources :tarefa_alunos
  resources :tarefas, except: [:index]
  resources :avatares
  resources :foruns_comentarios, except: [:index, :show]
  resources :foruns
  resources :usuario_curso
  resources :materiais, except: [:index]
  resources :cursos
  resources :ahoy_visits, except: [:new, :edit, :destroy]

  resources :modulos do
    collection do
      patch :sort
    end
  end

  resources :modulos_ordenacoes do
    collection do
      patch :sort
    end
  end
  

  resources :tema_cursos
  devise_for :admins, :skip => [:registrations]

  devise_scope :admin do
    authenticated :admin do
      root 'controle#controle_gestor', as: :authenticated_root
    end
  end
  
  resources :usuarios, :only => [:index, :edit, :update, :show]
  devise_for :usuarios, :path_prefix => 'my', controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations',
  }

  devise_scope :usuario do
    root 'usuarios/sessions#new'
  end  

  #Controle
  get 'inicial' => 'controle#inicial'
  get 'sobre' => 'controle#sobre'
  get 'controle_gestor' => 'controle#controle_gestor'
  get 'controle_professor' => 'controle#controle_professor'
  get 'desenvolvimento' => 'controle#desenvolvimento'
  get 'contato' => 'controle#contato'

  #Usuário Curso
  get 'busca_curso' => 'usuario_curso#busca_curso'
  get 'inscricao_curso' => 'usuario_curso#inscricao_curso'
  get 'notas_aluno' => 'usuario_curso#notas_aluno'
  get 'minhas_notas' => 'usuario_curso#minhas_notas'
  get 'ranking_usuario' => 'usuario_curso#ranking_usuario'
  get 'escolher_equipe' => 'usuario_curso#escolher_equipe'
  get 'cancelar_inscricao' => 'usuario_curso#cancelar_inscricao'
  get 'finalizar_curso' => 'usuario_curso#finalizar_curso'
  get 'atualizar_avatar' => 'usuario_curso#atualizar_avatar'
  get 'pendencias' => 'usuario_curso#pendencias'
  get 'minhas_conquistas' => 'usuario_curso#minhas_conquistas'
  get 'nota_total_alunos' => 'usuario_curso#nota_total_alunos'
 
  #Curso
  get 'curso_atual' => 'cursos#atualizar_curso_atual'
  get 'descricao' => 'cursos#descricao'
  get 'visualizar_curso' => 'cursos#visualizar_curso'
  get 'notas' => 'cursos#notas'
  get 'enviar_convite' => 'cursos#enviar_convite'
  post 'enviar_convite' => 'cursos#enviar_convite'
  
  get 'finalizar_completamente_curso' => 'cursos#finalizar_completamente_curso'

  get 'material_texto' => 'materiais#texto'
  
  get 'termo_uso' => 'usuarios#termo_uso'

  get 'equipe' => 'grupos_cursos#lista_participantes'

  get 'resultado_final_quiz' => 'quiz_respostas_alunos#resultado_final_quiz'

  get 'finalizar_quiz' => 'quizzes#finalizar_quiz'

  get 'graficos_pizza' => 'question_groups#graficos_pizza'

  get 'graficos_barra' => 'question_groups#graficos_barra'

  get 'faq_agile' => 'faqs#faq_agile'

  get 'faq_agile' => 'faqs#faq_agile'

  get 'visualizar_avatares' => 'avatares#visualizar_avatares'

  get 'tarefas_avaliar' => 'tarefa_avaliacao#tarefas_avaliar'

  #Conversas
  get 'conversas_professor' => 'conversas#conversas_professor'
  get 'conversas_assunto' => 'conversas#conversas_assunto'

  get 'cancelar_evento' => 'eventos#cancelar_evento'

  #CursoCertificado
  get 'gerar_certificado' => 'curso_certificados#gerar_certificado'
  get 'validar_certificado' => 'curso_certificados#validar_certificado'
  get 'certificado_validado' => 'curso_certificados#certificado_validado'

  mount RailsAdmin::Engine => '/administration', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Ckeditor::Engine => '/ckeditor'

  mount ActionCable.server => '/cable'
  
  mount Rapidfire::Engine => "/rapidfire"

  resources :question_groups do
    get 'results', on: :member

    resources :questions
    resources :answer_groups, only: [:new, :create, :show]
  end
  resources :questions
end

app/controllers/controle_controller.rb
class ControleController < ApplicationController
  before_action :authenticate_any!, :except => [:sobre, :contato]

  def inicial
  	@q = Curso.ransack(params[:q])
    @cursos_publicos = @q.result.where(publico: true, ativo: true).paginate(:page => params[:page], :per_page => 6).order('updated_at')

  	@meuscursos = UsuarioCurso.where(usuario_id: current_usuario).order('updated_at')
  	render layout: 'neutro'
  end

  def sobre
  	render layout: 'neutro'
  end

  def contato
  	render layout: 'neutro'
  end

  def desenvolvimento
    render layout: 'neutro'
  end

  def controle_professor
    authorize! :controle_professor,:controle
  end
  
  def controle_gestor
    authorize! :controle_gestor,:controle
  end

end

app/helpers/controle_helper.rb
module ControleHelper
end

app/views/controle/_aluno.html.erb
<nav id="sidebar" class="sidebar navbar-nav">
  <div class="sidebar-header sidebar-avatar">

    <% if @perfil.perfil == 'Aluno' %>
      <% if @perfil.avatar %>
        <p class="list-group-item text-center"><%= image_tag @perfil.avatar.imagem, class: "img-responsive img-thumbnail" %></p>
      <% else %>
        <p class="list-group-item text-center"><%= image_tag "missing.png", class: "img-responsive img-thumbnail" %></p>
      <% end %>
      <p class="list-group-item text-center perfil"> <%= link_to @perfil.nickname, @perfil %></p>
      <p class="list-group-item text-center perfil"><label>XP:</label> <%= pontuacao(@perfil) %></p>
      <p class="list-group-item text-center perfil"><label>Nível:</label> <%= @perfil.nivel.nome %></p>
      <% if @perfil.grupo_curso %>
        <p class="list-group-item text-center perfil"><label>Equipe:</label> <%= link_to @perfil.grupo_curso.nome_curso, equipe_url %></p>
        <p class="list-group-item text-center perfil"><label>XP Médio da Equipe:</label> <%= formata_pontos(@perfil.grupo_curso.pontuacao_media_equipe) %></p>
      <% else %>
        <p class="list-group-item text-center perfil"><%= link_to 'Escolher Equipe', escolher_equipe_url(id: @perfil.id), class: 'text-danger' %></p>
      <% end %>
      <p class="list-group-item text-center perfil"><label>Aproveitamento:</label> <%= formata_pontos(@perfil.porcentagem_aprovacao) %>%</p>
      <p class="list-group-item text-center perfil"><label>Status:</label> <%= @perfil.status_curso %></p>
    <% end %>
  </div>

  <ul class="navbar-nav bg-gradient-primary sidebar accordion" id="accordionSidebar">
    <li class="nav-item nav-sidebar">
      <%= link_to " Página principal", @current_usuario.curso_atual, {class: "fa fa-university fa-sm nav-link text-light"} %>
    </li>
    
    <li class="nav-item nav-sidebar">
      <%= link_to " Informações", descricao_path(id: @current_usuario.curso_atual), {class: "fa fa-info-circle fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Meu perfil", @perfil, {class: "fa fa-user fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Módulos", @current_usuario.curso_atual, {class: "fa fa-cubes fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Minhas notas", minhas_notas_path, {class: "fa fa-graduation-cap fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Recompensas", recompensas_path, {class: "fa fa-gift fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Minha equipe", equipe_path, {class: "fa fa-users fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Comunicados", comunicados_path, {class: "fa fa-bullhorn fa-sm nav-link text-light"} %>
    </li> 

    <li class="nav-item nav-sidebar">
      <%= link_to " Eventos", eventos_path, {class: "fa fa-calendar fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Chats", salas_chat_path, {class: "fa fa-comments fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Pesquisas", question_groups_path, {class: "fa fa-search fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Participantes", {controller: 'usuario_curso', action: 'index'}, class: "fa fa-user-circle fa-sm nav-link text-light" %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Professor(es)", conversas_path, {class: "fa fa-address-book fa-sm nav-link text-light"} %>
    </li>
  </ul>
</nav>

app/views/controle/_gestor.html.erb
<div class="col-md-2 col-sm-2 color-sidebar ">
    <nav id="sidebar" class="sidebar navbar-nav">		
		<ul class="navbar-nav bg-gradient-primary sidebar accordion" id="accordionSidebar">	
		
			<li class="nav-item">
				<br>
				<h4 class="agile"><a href="/"><i class="fa fa-wrench fa-lg "></i>Gerenciamento</a></h4>
			</li>
			<div class="dropdown-divider"></div>

			<li class="nav-item nav-sidebar">
				<a class="nav-link collapsed text-light" href="#" data-toggle="collapse" data-target="#collapse1"
					aria-expanded="true" aria-controls="collapse1">
					
					Cursos <span class="fa fa-plus-circle fa-sm"></span>
				</a>
				<div id="collapse1" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
					<div class="py-2 collapse-inner rounded bg-primary">
						<p class="menu"> <%= link_to " Áreas", areas_path, {class: "fa fa-thumb-tack fa-sm nav-link text-light"} %></p>
						<p class="menu"> <%= link_to " Temas", tema_cursos_path, {class: "fa fa-paint-brush fa-sm nav-link text-light"} %></p>
						<p class="menu"> <%= link_to " Cursos", cursos_path, {class: "fa fa-university fa-sm nav-link text-light"} %></p>
					</div>
				</div>
			</li>

			<li class="nav-item nav-sidebar">
				<a class="nav-link collapsed text-light" href="#" data-toggle="collapse" data-target="#collapse2"
					aria-expanded="true" aria-controls="collapse2">
					Badges <span class="fa fa-plus-circle fa-sm"></span>
				</a>
				<div id="collapse2" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
					<div class="py-2 collapse-inner rounded bg-primary">
						<p class="menu"><%= link_to " Badges", badges_path, {class: "fa fa-trophy fa-sm nav-link text-light"} %></p>
						<p class="menu"><%= link_to " Badges/Alunos", badges_alunos_path, {class: "fa fa-gear fa-sm nav-link text-light"} %></p>
					</div>
				</div>
			</li>

			<li class="nav-item nav-sidebar">
				<%= link_to " Níveis", niveis_path, {class: "fa fa-star-half-o fa-sm nav-link text-light"} %>
			</li>

			<li class="nav-item nav-sidebar">
				<%= link_to " Grupos", grupos_path, {class: "fa fa-user-circle fa-sm nav-link text-light"} %>
			</li>

			<li class="nav-item nav-sidebar">
				<%= link_to " Avatares", avatares_path, {class: "fa fa-user-secret fa-sm nav-link text-light"} %>
			</li>

			<li class="nav-item nav-sidebar">
				<a class="nav-link collapsed text-light" href="#" data-toggle="collapse" data-target="#collapse3"
					aria-expanded="true" aria-controls="collapse3">
					
					Artefatos <span class="fa fa-plus-circle fa-sm"></span>
				</a>
				<div id="collapse3" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
					<div class="py-2 collapse-inner rounded bg-primary">
						<p class="menu"><%= link_to " Artefatos", artefatos_path, {class: "fa fa-beer fa-sm nav-link text-light "} %></p>
						<p class="menu"><%= link_to " Artefatos/Alunos", artefatos_alunos_path, {class: "fa fa-cog fa-sm nav-link text-light"} %></p>
					</div>
				</div>
			</li>

			<li class="nav-item nav-sidebar">
				<%= link_to " Usuários", usuarios_path, {class: "fa fa-users fa-sm nav-link text-light"} %>
			</li>

			<li class="nav-item nav-sidebar">
				<%= link_to " FAQ", faqs_path, {class: "fa fa-question-circle fa-sm nav-link text-light"} %>
			</li>

			<li class="nav-item nav-sidebar">
				<%= link_to " Acessos", ahoy_visits_path, {class: "fa fa-eye fa-sm nav-link text-light"} %>
			</li>

			<li class="nav-item nav-sidebar">
				<%= link_to " Rails Admin", rails_admin_url, {class: "fa fa-diamond fa-sm nav-link text-light", data: { turbolinks: false }} %>
			</li>
		</ul>
	</nav>
	<br>
</div>

<div class="col-md-10 col-sm-10">
	<% if notice %>
		<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
		<p class="alert alert-danger"><%= alert %></p>
	<% end %>
	<%= yield %>
	<br>
	<br>
</div>

app/views/controle/_menu_direito.html.erb
<% if @perfil %>

	
	<div class="alert alert-success alert-lateral">
		<%= link_to " Voltar para Módulos", @current_usuario.curso_atual, {class: "fa fa-arrow-circle-o-left fa-sm nav-link text-dark"} %>
	</div>

	<% if @perfil.perfil == 'Aluno' %>

		<div class="alert alert-warning alert-lateral">
			<%= link_to " Conquistas", minhas_conquistas_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: "fa fa-trophy fa-sm nav-link text-dark"} %>
		</div>

		<% if @perfil.curso.recompensas.exists? %>
			<div class="alert alert-danger alert-lateral">
				<%= link_to " Recompensas", recompensas_path, {class: "fa fa-gift fa-sm nav-link text-dark"} %>
			</div>
		<% end %>
	<% end %>
	
	<% if  !@perfil.evento.empty? %>

		<div class="alert alert-primary alert-lateral">
			<li class="nav-item">
			  <i class="fa fa-calendar fa-sm nav-link text-secondary"> Eventos </i>
			</li>
		
			<% @perfil.evento.each do |evento| %>
				<li class="nav-item ">
		    		<%= link_to evento.data.strftime("%d/%m/%Y"), evento, class: 'nav-link' %>
		    	</li>
		    <% end %>
		    <li class="nav-item text-center"><%= link_to 'Ver todos', eventos_path, class: 'btn btn-sm btn-primary btn-block' %></li>
		</div>

	<% end %>  

	<div class="alert alert-success alert-lateral">
		<li class="nav-item">
			<i class="fa fa-rocket fa-sm nav-link text-dark"> Ranking</i>
		</li>
	  	
		<% @perfil.ranking.first(10).each_with_index do |aluno, index| %>
			<li class="nav-item">
				<%= link_to "#{index+1}º  #{aluno[0].nickname}", aluno[0], class: 'nav-link' %>
			</li>
		<% end %>
		
		<li class="nav-item text-center"><%= link_to 'Ver todos', ranking_usuario_path, class: 'btn btn-sm btn-success btn-block' %></li>
	</div>

	<% if @perfil.grupo_curso %>
		<% if  !@perfil.ranking_equipe.empty? %>
			<div class="alert alert-info alert-lateral">
				<li class="nav-item">
					<i class="fa fa-users fa-sm nav-link text-dark"> Equipes</i>
				</li>
					
				<% @perfil.ranking_equipe.each_with_index do |equipe, index| %>
					<li class="nav-item">
						<%= "#{index+1}º #{equipe[0]}: " + formata_pontos(equipe[1]).to_s + "XP" %>
					</li>
				<% end %>
			</div>
		<% end %>
	<% end %>

	<% if  @perfil.forum %>
		<div class="alert alert-warning alert-lateral">
			<li class="nav-item">
        <%= link_to " Fóruns", foruns_path, {class: "fa fa-clipboard fa-sm nav-link text-dark"} %>
      </li>
    </div>
	<% end %> 
	
	<% if  @perfil.chat %>

		<div class="alert alert-warning alert-lateral">
			<li class="nav-item">
				<%= link_to " Chats", salas_chat_path, {class: "fa fa-comments fa-sm nav-link text-dark"} %>
			</li>
		</div>

	<% end %>  

	<% if  @perfil.perfil == 'Aluno' %>

		<% if  @perfil.pesquisa %>

			<div class="alert alert-primary alert-lateral">
				<li class="nav-item">
					<%= link_to " Pesquisas", question_groups_path, {class: "fa fa-search fa-sm nav-link text-dark"} %>
				</li>
			</div>

		<% end %>

		<div class="alert alert-danger alert-lateral">
			<li class="nav-item">
				<%= link_to " Pendências", pendencias_path(id: @perfil.id), {class: "fa fa-exclamation-triangle fa-sm nav-link text-dark"} %>
			</li>
		</div>

		<% if  @perfil.notificacao %>

			<div class="alert alert-info alert-lateral">
				<li class="nav-item">
					<%= link_to " Notificações", notificacoes_path, {class: "fa fa-bell fa-sm nav-link text-dark"} %>
				</li>
			</div>

		<% end %>

	<% end %>

	<% if  @perfil.perfil == 'Professor' %>
		<div class="alert alert-danger alert-lateral">
			<li class="nav-item">
				<%= link_to " Tarefas a Avaliar", tarefas_avaliar_path, {class: "fa fa-exclamation-triangle fa-sm nav-link text-dark"} %>
			</li>
		</div>
	<% end %>
	
<% end %>

app/views/controle/_professor.html.erb
<nav id="sidebar" class="sidebar navbar-nav">
  <div class="sidebar-header sidebar-avatar">
    <% if @perfil.perfil == 'Professor' %>
      <% if @perfil.avatar %>
        <p class="list-group-item text-center"><%= image_tag @perfil.avatar.imagem, class: "img-responsive img-thumbnail" %></p>
      <% else %>
        <p class="list-group-item text-center"><%= image_tag "missing.png", class: "img-responsive img-thumbnail" %></p>
      <% end %>  
      <p class="list-group-item text-center perfil"> <%= link_to @perfil.nickname, @perfil %></p>
      
      <% if @perfil.grupo_curso %>
        <p class="list-group-item text-center perfil"><label>Equipe:</label> <%= link_to @perfil.grupo_curso.nome_curso, @perfil.grupo_curso %></p>
      <% else %>
        <p class="list-group-item text-center perfil"><%= link_to 'Escolher Equipe', escolher_equipe_url(id: @perfil.id), class: 'text-danger' %></p>
      <% end %>
      
    <% end %>      
  </div>

  <ul class="navbar-nav bg-gradient-primary sidebar accordion" id="accordionSidebar">
  
    <li class="nav-item nav-sidebar">
      <h4 class="agile"><i class="fa fa-wrench fa-lg "></i>Configuração</h4>
    </li>
    <div class="dropdown-divider"></div>
    <li class="nav-item nav-sidebar">
      <%= link_to " Página principal", @current_usuario.curso_atual, {class: "fa fa-university fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Informações", descricao_path(id: @current_usuario.curso_atual), {class: "fa fa-info-circle fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Meu perfil", @perfil, {class: "fa fa-user fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Equipes", grupos_cursos_path, {class: "fa fa-user-circle fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Módulos", modulos_path, {class: "fa fa-cubes fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Recompensas", recompensas_path, {class: "fa fa-gift fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Notas/Missão", notas_path, {class: "fa fa-bullseye fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Notas da turma", nota_total_alunos_path, {class: "fa fa-graduation-cap fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Participantes", {controller: 'usuario_curso', action: 'index'}, class: "fa fa-users fa-sm nav-link text-light" %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Comunicados", comunicados_path, {class: "fa fa-bullhorn fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Eventos", eventos_path, {class: "fa fa-calendar fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Chats", salas_chat_path, {class: "fa fa-comments fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Pesquisas", question_groups_path, {class: "fa fa-search fa-sm nav-link text-light"} %>
    </li>

    <li class="nav-item nav-sidebar">
      <%= link_to " Mensagens", conversas_path, {class: "fa fa-commenting fa-sm nav-link text-light"} %>
    </li>             

    <li class="nav-item nav-sidebar">
      <%= link_to " Convidar", enviar_convite_path, {class: "fa fa-envelope fa-sm nav-link text-light"} %>
    </li>

  </ul>
</nav>

app/views/controle/controle_gestor.html.erb
<div class="card">

  <div class="card-header">Gerenciamento do AGILE</div>

  <div class="text-center">
    <br>
    <%= image_tag ("coelho2.png"), class: "img-responsive", width: "100", height: "100" %>
    <h1 class="agile text-primary">AGILE</h1>
  </div> 

  <br>
  <div class="alert alert-danger" role="alert">
    Em caso de dúvidas, consulte o Manual do Administrador.
  </div>

</div>

app/views/controle/controle_professor.html.erb
<div class="card">

  <div class="card-header">Gerenciamento do Curso</div>
  
  <ul class="list-group">
    <li class="list-group-item"><b>Curso:</b> <%= current_usuario.curso_atual.nome %></li> 
    <li class="list-group-item"><b>Descrição:</b> <%= current_usuario.curso_atual.descricao.to_s.html_safe %></li> 
  </ul>

  <br>
  <div class="alert alert-danger" role="alert">
    Em caso de dúvidas, consulte o Manual do Professor.
  </div>
  
  <div class="card-footer text-muted">
    <%= link_to 'Voltar', inicial_path, class: "btn btn-md btn-secondary" %>
  </div>

</div>

app/views/controle/inicial.html.erb
<div class="card">

 	<div id="content-wrapper">

        <div class="container-fluid">
        	<br>
        	<div class="text-center">
        		<% if current_admin  %>
			  		<%= link_to 'Gerenciamento do AGILE', controle_gestor_path, class: "btn btn-md btn-danger" %>
			  	<% else %>
			  		<%= link_to 'Me inscrever em um curso com código de acesso', {controller: 'usuario_curso', action: 'busca_curso'}, class: "btn btn-md btn-success" %>
			  	<% end %>
			</div>
			<br>
			<!-- Breadcrumbs-->
			<ol class="breadcrumb">
			<li class="breadcrumb-item text-center">Meus Cursos</li>
			</ol>
		
			<!-- Icon Cards-->

			<div class="row">
				<% @meuscursos.each do |curso| %>
					<div class="col-xl-3 col-sm-6 mb-3">
						<div class="card text-white o-hidden h-100 curso">
							<div class="card-body">
								<div><%= curso.curso.nome %></div>
							</div>
							<div class="card-footer bg-primary text-white">
								<%= link_to 'Acessar', {controller: 'cursos', action: 'atualizar_curso_atual', curso_id: curso.curso.id}, class: 'linkcurso' %>
							</div>
						</div>
					</div>
				<% end %>
			</div>

			<ol class="breadcrumb">
				<li class="breadcrumb-item text-center">Buscar Cursos Públicos</li>
			</ol>

			<%= search_form_for @q, url: inicial_path do |f| %>
				<div class="card-body">

					<div class="row">
						<div class="col-lg-5">
							<div class="input-group mb-3">
								<div class="input-group-prepend">
								<span class="input-group-text" id="basic-addon1">Nome</span>
								</div>
								<%= f.search_field :nome_cont, :class => 'form-control'  %>
							</div>
						</div>

						<div class="col-lg-3">
							<div class="input-group mb-3">
								<div class="input-group-prepend">
								<span class="input-group-text" id="basic-addon1">Código de Acesso</span>
								</div>
								<%= f.search_field :codigo_acesso, :class => 'form-control' %>
							</div>
						</div>

						<div class="col-lg-4">
							<div class="input-group mb-3">
								<div class="input-group-prepend">
								<span class="input-group-text" id="basic-addon1">Área</span>
								</div>
								<%= f.select :area_id_eq,  options_from_collection_for_select(Area.where(ativa: true), "id", "nome"), :include_blank => "Todas", :class => 'form-control', id: 'custom-select' %>
							</div>
						</div>
					</div>     
				</div>
				
				<div class="text-center">
				<button class="btn btn-primary link search-btn" ><% submit_tag "" %>Pesquisar</button>
				</div>
			<% end %>
          
		  
			<% if not @cursos_publicos.empty? %>
				<div class="row">
					<% @cursos_publicos.each do |curso| %>
						<div class="col-xl-3 col-sm-6 mb-3">
						<div class="card text-white curso o-hidden h-100">
							<div class="card-body">
								<div><%= curso.nome %></div>
							</div>
							<div class="card-footer bg-primary text-white">
							<%= link_to 'Visualizar', {controller: 'cursos', action: 'visualizar_curso', id: curso.id}, class: 'linkcurso' %>
							</div>
						</div>
						</div>
					<% end %>
				</div>
			<% end %>

        </div>
    </div>
</div>